### PR TITLE
Please added the update translation for german user

### PR DESCRIPTION
**Pull request by Matze1985**
Nice greetings, the other commit was a test. BR

### CODE REVIEW

**Comment by jamorham** [comment]
Can you give me a brief summary of the changes and reason for them? Thanks.

**Comment by Matze1985** [comment]
Here i tested for INT version long strings, but the PROD version is a other. 
My commit is not in the Google Play app for beta user integrated, here is the right XML for this.

See https://github.com/pimpimmi/LibreAlarm/pull/24 is not commited, we have here a conflict with the right translation.

**Comment by jamorham** [comment]
What about alternatives like: "Hoch-Alarm" and "Niedrig-Alarm" ?

**Comment by Matze1985** [comment]
Please change the strings to:

<string name="alarm_disabled_low_text" formatted="false">Min Glukosealarm deakt bis: %s</string>
<string name="alarm_disabled_high_text" formatted="false">Max Glukosealarm deakt bis: %s</string>
<string name="settings_alarm_high_title">Max Glukosewert</string>
<string name="settings_alarm_low_title">Min Glukosewert</string>
<string name="settings_snooze_high_title">Max Glukosealarm</string>
<string name="settings_snooze_low_title">Min Glukosealarm</string>

See here https://github.com/jamorham/LibreAlarm/pull/1/commits/a44c78adfa5069e42d72907aa325379d699dc859

This are the corrected prod app strings from the app.

**Pull request merged**
