### PR TITLE
Send all 43 blocks to xDrip for processing.

### PR DESCRIPTION
**Pull request by tzachi-dar**

### CODE REVIEW

**Comment by jamorham** [comment]
Okay, I can see what this is intended to do. Have you been able to test it with the SW3 ?

**Comment by tzachi-dar** [comment]
This has been tested with the sony sw3.

**Comment by blocklist** [comment]
Hi, i have used the changed code today. I see no differents, but it works for me. There are no Problemes on LibreAlarm self and xdrip works also fine. Setup: swr50 with LibreAlarm, xDrip+ (build 04.01.18), no wear-collector.

**Review by jamorham — APPROVED** [review]
Looks like it should work assuming buildtools change doesn't introduce anything weird. I will merge now.

**Comment by dideldum** [comment]
Which Android Wear version is appropiate for this version?
I tried with Libre Alarm 1.08 various Android Wear versions, but no version was completely stable regarding the connection to the watch. Android Wear 2.0.0.147108189 was the best, but also failed after about 11 hours, Android Wear 2.0.0.151760697 was worse, it failed after 3-4 hours, and the actual Android Wear version from the App Store (2.7.0.xxxx) was very bad, it failed within 1 hour. Android Wear didn't reconnect then, thus also making Libre Alarm failing.
Would be nice to hear from @tzachi-dar or @blocklist, which Android Wear version they used.

**Comment by adardexcom** [comment]
I'll check it once I'm home.
Did previous versions worked for you better?

**Comment by blocklist** [comment]
I use 2.0.0.147108189, the from Nov 2017 works also, but needs more battery. The latest from Dec or so, makes the Battery so much drain. 
I know, that a software update/patch from samsung for the s7 in middle of last year (08/09/10 2017 or so) made big Problems no matter with which version. The Watch lost all few hours the connection and needs a reboot of the mobile phone.

**Comment by tzachi-dar** [comment]
I"m using a nexus 5 and android version 2.7.0.177669439.gms

Not using it continuously for a long time, but it seems to work well.

**Pull request merged**
